services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    privileged: true
    expose:
      - 8080
    networks:
      - monitoring
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    expose:
      - 9100
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro,rslave
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host/root
      - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/run/docker/.+)($|/)

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    expose:
      - 9090
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=7d
      - --web.enable-lifecycle
      - --enable-feature=exemplar-storage
      - --enable-feature=auto-reload-config
      - --auto-gomaxprocs
      - --auto-gomemlimit


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - monitoring
      - traefik_public
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
    labels:
      - traefik.enable=true

      # -------------------------------
      # HTTP ROUTER
      # -------------------------------
      - traefik.http.routers.grafana-http.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.routers.grafana-http.entrypoints=http
      
      # -------------------------------
      # HTTPS ROUTER
      # -------------------------------
      - traefik.http.routers.grafana-https.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.routers.grafana-https.entrypoints=https
      - traefik.http.routers.grafana-https.tls=true
      - traefik.http.routers.grafana-https.tls.certresolver=le
      - traefik.http.routers.grafana-https.service=grafana-service

      # -------------------------------
      # HTTP â†’ HTTPS MIDDLEWARE
      # -------------------------------
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.grafana-http.middlewares=https-redirect

      # -------------------------------
      # SERVICE
      # -------------------------------
      - traefik.http.services.grafana-service.loadbalancer.server.port=3000

      # -------------------------------
      # RATE LIMIT MIDDLEWARE
      # limit: 200 req/s
      # -------------------------------
      - traefik.http.routers.grafana-https.middlewares=grafana-ratelimit
      - traefik.http.middlewares.grafana-ratelimit.ratelimit.average=300
      - traefik.http.middlewares.grafana-ratelimit.ratelimit.burst=400

networks:
  monitoring:
    driver: bridge
  traefik-public:
    external: true

volumes:
  prometheus_data:
  grafana_data:
